name: Setup @aws-amplify/cli
description: Installs the @aws-amplify/cli npm package

author: "philip-gai"
branding:
  icon: "code"
  color: "yellow"

inputs:
  cli_version:
    required: false
    default: "latest"
  node_version:
    required: true
  cache_dependencies:
    required: true
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Setup node ${{ inputs.node_version }}
      uses: actions/setup-node@v2
      with:
        node-version: "${{ inputs.node_version }}"
    - if: inputs.cache_dependencies == 'true'
      name: Cache node modules
      uses: actions/cache@v2
      env:
        cache-name: aws-amplify-cli-cache-node-modules
      with:
        # npm cache files are stored in `~/.npm` on Linux/macOS
        path: ~/.npm
        key: ${{ runner.os }}-amplify-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-amplify-${{ env.cache-name }}-
          ${{ runner.os }}-amplify-
          ${{ runner.os }}-
    - name: Install @aws-amplify/cli@${{ inputs.cli_version }}
      shell: bash
      run: |
        npm install -g @aws-amplify/cli@${{ inputs.cli_version }}
